services:
  postgres:
    image: postgres:latest
    container_name: fast-api-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app_network

  app:
    build: .
    container_name: fast-api-app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_DB}:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    ports:
      - "8001:8001"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
